import test from 'ava';
import {Buffer} from 'node:buffer';
import {parseRootElementSize} from '../../source/integrations/figma/handoff-parse.js';
import {readPngSize} from '../../source/commands/verify-screenshots.js';

test('parseRootElementSize: extracts width/height from first <instance>', t => {
	t.deepEqual(
		parseRootElementSize('<instance id="1" width="1440" height="900" />'),
		{width: 1440, height: 900},
	);
});

test('parseRootElementSize: extracts width/height from first <frame>', t => {
	t.deepEqual(
		parseRootElementSize('<frame id="1" width="1440" height="900" />'),
		{width: 1440, height: 900},
	);
});

test('parseRootElementSize: handles attributes in any order', t => {
	t.deepEqual(
		parseRootElementSize(
			'<instance height="900" name="Frame" width="1440" id="1" />',
		),
		{width: 1440, height: 900},
	);
});

test('parseRootElementSize: skips XML prolog and matches the first real element', t => {
	t.deepEqual(
		parseRootElementSize(
			'<?xml version="1.0" encoding="UTF-8"?>\n<frame width="100" height="200" />',
		),
		{width: 100, height: 200},
	);
});

test('parseRootElementSize: skips comments before the first element', t => {
	t.deepEqual(
		parseRootElementSize(
			'<!-- generated by figma --><instance width="100" height="200" />',
		),
		{width: 100, height: 200},
	);
});

test('parseRootElementSize: returns null when no element is present', t => {
	t.is(parseRootElementSize('<?xml version="1.0"?>'), null);
});

test('parseRootElementSize: returns null when one attr is missing', t => {
	t.is(parseRootElementSize('<instance id="1" width="1440" />'), null);
});

test('parseRootElementSize: rejects non-numeric values', t => {
	t.is(parseRootElementSize('<instance width="abc" height="100" />'), null);
});

test('parseRootElementSize: matches the FIRST element only', t => {
	const xml =
		'<instance width="100" height="200" /><instance width="999" height="999" />';
	t.deepEqual(parseRootElementSize(xml), {width: 100, height: 200});
});

test('readPngSize: parses IHDR width/height', t => {
	const png = Buffer.alloc(33);
	png.set([137, 80, 78, 71, 13, 10, 26, 10], 0);
	png.writeUInt32BE(13, 8); // IHDR length
	png.write('IHDR', 12, 'ascii');
	png.writeUInt32BE(1440, 16);
	png.writeUInt32BE(900, 20);
	t.deepEqual(readPngSize(png), {width: 1440, height: 900});
});

test('readPngSize: returns null on too-small buffer', t => {
	t.is(readPngSize(Buffer.alloc(10)), null);
});

test('readPngSize: returns null on missing PNG signature', t => {
	const buf = Buffer.alloc(33);
	buf.write('IHDR', 12, 'ascii');
	t.is(readPngSize(buf), null);
});

test('readPngSize: returns null when IHDR chunk is missing', t => {
	const png = Buffer.alloc(33);
	png.set([137, 80, 78, 71, 13, 10, 26, 10], 0);
	png.write('NOPE', 12, 'ascii');
	t.is(readPngSize(png), null);
});
